//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoCanjeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats
    {
        public Chats()
        {
            this.Chats_Detalles = new HashSet<Chats_Detalles>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Usuario_Emisor { get; set; }
        public Nullable<int> Usuario_Receptor { get; set; }
        public Nullable<System.DateTime> Fecha_Ultimo_Mensaje { get; set; }
        public string Ultimo_Mensaje { get; set; }
    
        public virtual ICollection<Chats_Detalles> Chats_Detalles { get; set; }
    }
}
