//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoCanjeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chats_Detalles
    {
        public int Id { get; set; }
        public Nullable<int> Usuario_Emisor { get; set; }
        public Nullable<int> Usuario_Receptor { get; set; }
        public Nullable<System.DateTime> Fecha_Mensaje { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> IdChat { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
