//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoCanjeWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MundoCanjeDBEntities : DbContext
    {
        public MundoCanjeDBEntities()
            : base("name=MundoCanjeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categorias> Categorias { get; set; }
        public DbSet<Chats> Chats { get; set; }
        public DbSet<Chats_Detalles> Chats_Detalles { get; set; }
        public DbSet<Despublicaciones_Tipos> Despublicaciones_Tipos { get; set; }
        public DbSet<Notificaciones> Notificaciones { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<Pedidos_Estados> Pedidos_Estados { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<Productos_Estados> Productos_Estados { get; set; }
        public DbSet<Productos_Tipos> Productos_Tipos { get; set; }
        public DbSet<Terminos> Terminos { get; set; }
        public DbSet<Usuarios_Tipos> Usuarios_Tipos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Preguntas_Frecuentes> Preguntas_Frecuentes { get; set; }
        public DbSet<Planes> Planes { get; set; }
    }
}
